name: Cleanup Old Builds

on:
  workflow_dispatch:

jobs:
  cleanup:
    name: Cleanup
    runs-on: ubuntu-latest
    steps:
      - name: Cleanup
        id: cleanup
        uses: dev-drprasad/delete-older-releases@v0.3.2
        with:
          #          repo: <owner>/<repoName> # defaults to current repo
          keep_latest: 3
          #          keep_min_download_counts: 1 # Optional parameters
          #          delete_expired_data: 10 # Optional parameters
          delete_tag_pattern: ^v*$ # Optional parameters
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
