name: Release

on:
  push:
    branches: [ main, beta ]

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write
      issues: read

    steps:
      - uses: actions/checkout@v3
        id: checkout
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/setup-node@v3
        id: install_node
        with:
          node-version: 20.x

      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: |
            **/node_modules
            **/.eslintcache
            ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install Deps
        id: install_deps
        run: yarn install --frozen-lockfile

      - name: Release
        id: release
        run: |
          yarn ci:token
          yarn release
        env:
          NODE_ENV_TOKEN: ${{ secrets.RELEASE_TOKEN }}
          ORGANIZATION: ${{ github.repository_owner }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
